version: '3.8'

services:
  # Backend - NestJS API
  ministraciones-backend:
    build:
      context: ./ministraciones_bk
      dockerfile: Dockerfile
    container_name: ministraciones-backend
    ports:
      - "3011:3011"
    environment:
      # Database
      - POSTGRES_HOST=172.16.35.75
      - POSTGRES_PORT=32768
      - POSTGRES_USER=maquio
      - POSTGRES_PASSWORD=maquio92
      - POSTGRES_DATABASE=siag_dev
      
      # JWT
      - JWT_SECRET=L0ng_s3cr3t_p4ssw0rd_G@l@xy2025
      - JWT_EXPIRATION=1h
      
      # App
      - API_PORT=3011
      - MODE=DEV
      - RUN_MIGRATIONS=false
      - API_URL2=http://172.16.35.75:3001/api
    restart: unless-stopped
    networks:
      - ministraciones-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3011/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Frontend - Next.js
  ministraciones-frontend:
    build:
      context: ./ministraciones
      dockerfile: Dockerfile
    container_name: ministraciones-frontend
    ports:
      - "3010:3010"
    environment:
      # Database (for any direct connections)
      - POSTGRES_HOST=172.16.35.75
      - POSTGRES_PORT=32768
      - POSTGRES_USER=maquio
      - POSTGRES_PASSWORD=maquio92
      - POSTGRES_DATABASE=siag_dev
      
      # JWT
      - JWT_SECRET=L0ng_s3cr3t_p4ssw0rd_G@l@xy2025
      - JWT_EXPIRATION=1h
      
      # App
      - PORT=3010
      - API_PORT=3011
      - API_URL=http://172.16.35.75:3011/
      - API_URL2=http://172.16.35.75:3001
      - MODE=DEV
      - IS_DEV_MODE=true
      - RUN_MIGRATIONS=false
      - NEXT_PUBLIC_API_BASE=http://172.16.35.75:3011
    depends_on:
      - ministraciones-backend
    restart: unless-stopped
    networks:
      - ministraciones-network

networks:
  ministraciones-network:
    driver: bridge

volumes:
  ministraciones-data:
